### ISSUE TITLE
[Question] I have a question regarding 'master' branch and 'master-enough' branch.

### ISSUE THREAD

**Issue by J-S-Kim** [EMDC-OS/CXL-AutoNUMA#8]
How do the commits in the 'master-enough' branch differ from those in the 'master' branch?

I am curious about the intention behind this branch and the possibility of integration with the master branch in the future.

**Comment by nicedavid98** [comment]
hello,

You can think of the 'master' branch as the default branch. 
The 'master-enough' branch checks whether the upper tier memory is free when promoting a page, and this is a branch that has relaxed the criteria.
