### ISSUE TITLE
Question regarding the default value of the variable called 'sysctl_numa_balancing_promote_throughput'.

### ISSUE THREAD

**Issue by YoungHoonJun** [EMDC-OS/CXL-AutoNUMA#9]
It seems that the default value of 'sysctl_numa_balancing_promote_throughput' is currently set to 1000KB. Is there a reason for setting it to this value?

**Comment by nicedavid98** [comment]
hello,
So far, we have set the best value empirically.
but the minimum standard was set to a number to reduce the number of migrated pages compared to the existing autonuma2.
